services:
  TwelveFactorMicroservicePolley:
    image: bigpolshark/image12factormicroservicepolley:latest
    ports:
      - "40080:80"
      - "40443:443"
    networks:
      - TwelveFactorMicroservicePolleyNetwork
    environment:
      - MapQuestAPIKey=dNf3SB306SveGv0goTvIhxU4JSJatW4g
      - dbName=TwelveFactorMicroservicePolleyNetworkDB
      - dbUser=sa
      - dbPW=MsSqlServer1#

  TwelveFactorMicroservicePolleyNetworkDB:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=MsSqlServer1#
    networks:
      - TwelveFactorMicroservicePolleyNetwork

networks: 
   TwelveFactorMicroservicePolleyNetwork: